# @package _global_

defaults:
  - _self_
  - data: cifar.yaml # choose datamodule with `test_dataloader()` for evaluation
  - model: cifar.yaml
  - trainer: default.yaml
  - paths: default.yaml
  
  
  - experiment: null

task_name: "infer"

tags: ["dev"]
ckpt_path:  ${paths.root_dir}/outputs/2023-06-18/14-05-30/lightning_logs/version_0/checkpoints/epoch=1-step=704.ckpt